import {Worker as NodeWorker} from 'node:worker_threads';import assert from 'node:assert/strict';import {MatchEngine} from '../js/engine.js';import {STRATEGIES} from '../js/strategies.js';import {metrics} from '../js/metrics.js';import {summaryRow,roundCSV} from '../js/exports.js';
class WebWorkerAdapter{
 constructor(url){this.worker=new NodeWorker(new URL('./node-worker-bridge.cjs',import.meta.url),{workerData:{url:url.href}});this.worker.on('message',data=>this.onmessage?.({data}));this.worker.on('error',error=>this.onerror?.({message:error.message,preventDefault(){}}));}
 postMessage(data){this.worker.postMessage(data);}terminate(){this.worker.terminate();}
}
globalThis.Worker=WebWorkerAdapter;
const s=x=>{const b=STRATEGIES.find(s=>s.id===x);return b?{...b,filename:b.id+'.py'}:{id:'upload',name:'uploaded',source:x,filename:'test.py'};};
const run=(a,b,n=10,seed='test')=>new MatchEngine().run({a:s(a),b:s(b),rounds:n,seed});
for(const [a,b,expected] of [['always-share','always-share',[30,30]],['always-keep','always-share',[50,10]],['always-keep','always-keep',[20,20]],['always-share','always-keep',[10,50]]]){const r=await run(a,b);assert.equal(r.status,'complete',r.error);assert.deepEqual([r.rows.at(-1).total_a,r.rows.at(-1).total_b],expected);console.log('PASS exact outcome',a,b);}
const r1=await run('random','random',50),r2=await run('random','random',50);assert.equal(r1.status,'complete',r1.error);assert.deepEqual(r1.rows,r2.rows);assert.notEqual(r1.seed_a,r1.seed_b);console.log('PASS seeded repeatability, separate side seeds');
const state='n=0\ndef space_exploration_strategy(h,r,m):\n global n\n n+=1\n assert n==r\n return "S" if n==1 else "K"';
const a=await run(state,state),b=await run(state,state);assert.equal(a.status,'complete',a.error);assert.deepEqual(a.rows,b.rows);assert.equal(a.rows[0].outcome,'SS');console.log('PASS self-play isolation, module reset, validation isolation');
const perspective='def space_exploration_strategy(h,r,m):\n assert len(h)==r-1\n assert m==1.0\n for mine, theirs in h: assert mine=="S" and theirs=="K"\n h.clear()\n return "S"';
for(const [left,right] of [[perspective,'always-keep'],['always-keep',perspective]]){const r=await run(left,right);assert.equal(r.status,'complete',r.error);}console.log('PASS both history perspectives, history copies, numbering and previous-round-only decisions');
for(const source of ['x =','import os','x=1','def space_exploration_strategy(a): return "S"']){const r=await run(source,'always-share');assert.equal(r.status,'incomplete');assert.equal(r.rows.length,0);}console.log('PASS syntax, imports, missing callable, incompatible signature');
const broken=await run('def space_exploration_strategy(h,r,m):\n return "S" if r<4 else "invalid"','always-share');assert.equal(broken.status,'incomplete');assert.equal(broken.rows.length,3);assert.match(broken.error,/round 4/);assert.equal(summaryRow(broken).winner,'');console.log('PASS runtime error preserves prefix, no winner');
const infinite=await run('def space_exploration_strategy(h,r,m):\n while True: pass','always-share');assert.match(infinite.error,/timeout/);assert.equal((await run('always-share','always-share')).status,'complete');console.log('PASS timeout, worker termination, next-run recovery');
const e=new MatchEngine();const cancelled=await e.run({a:s('random'),b:s('random'),rounds:100,seed:'cancel'},n=>{if(n===10)e.cancel();});assert.equal(cancelled.status,'cancelled');assert.equal(cancelled.rows.length,10);assert.equal((await run('always-share','always-share')).status,'complete');console.log('PASS cancellation, prefix preservation, recovery');
const long=await run('random','grudger',5000);assert.equal(long.status,'complete',long.error);assert.equal(long.rows.length,5000);const m=metrics(long.rows),row=summaryRow(long);assert.equal(row.total_a,long.rows.reduce((sum,r)=>sum+r.points_a,0));assert.equal(row.total_b,long.rows.reduce((sum,r)=>sum+r.points_b,0));assert.equal(row.completed_rounds,5000);assert.equal(roundCSV(long).trim().split('\r\n').length,5001);assert.equal(['SS','SK','KS','KK'].reduce((sum,o)=>sum+m[`outcome_${o}_count`],0),5000);console.log('PASS 5,000-round computation and export reconciliation');
console.log('ALL ACTUAL PYODIDE WORKER TESTS PASSED');
