import {STRATEGIES} from './strategies.js';
import {RULES,hashSource} from './rules.js';
import {MatchEngine} from './engine.js';
import {metrics,summary} from './metrics.js';
import {roundCSV,summaryCSV,download} from './exports.js';
import {Playback,drawChart} from './playback.js';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const factions=['Orion Space Agency (OSA)','Terra Galactic Federation (TGF)'];
let record=null,engine=null,busy=false,uploads={},reading=0;
const seed=()=>Array.from(crypto.getRandomValues(new Uint32Array(2)),x=>x.toString(16)).join('-');
$('seed').value=seed();
$('strategy-inputs').innerHTML=['a','b'].map((s,i)=>`<div class="strategy"><div class="side-title ${s}"><strong>STRATEGY ${s.toUpperCase()}</strong><span id="badge-${s}">${i?'TGF':'OSA'}</span></div><label for="select-${s}">Strategy</label><select id="select-${s}">${STRATEGIES.map((b,j)=>`<option value="${b.id}" ${j===i?'selected':''}>${b.name}${b.id==='tit-for-tat'?' · benchmark only':''}</option>`).join('')}<option value="upload">Upload Python file…</option></select><div id="upload-${s}" hidden><label>Python file<input type="file" id="file-${s}" accept=".py"></label><p id="file-status-${s}" class="help">Recommended: teamname_strategyname.py · up to 100 KB</p></div><p class="help" id="description-${s}"></p><details><summary>View Python source</summary><pre id="source-${s}"></pre></details><details><summary>Team & faction labels</summary><label>Team name (optional)<input id="team-${s}" maxlength="80" placeholder="Team ${s.toUpperCase()}"></label><label>Faction<select id="label-${s}">${factions.map((f,j)=>`<option ${j===i?'selected':''}>${f}</option>`).join('')}<option>Unassigned</option></select></label></details></div>`).join('');
function selected(s){const id=$(`select-${s}`).value;if(id==='upload'){if(!uploads[s])throw Error(`Strategy ${s.toUpperCase()}: choose a Python file first.`);return uploads[s];}const b=STRATEGIES.find(b=>b.id===id);return {...b,filename:b.id.replaceAll('-','_')+'.py'};}
function preview(s){$(`badge-${s}`).textContent=$(`label-${s}`).value.includes('(OSA)')?'OSA':$(`label-${s}`).value.includes('(TGF)')?'TGF':'—';const upload=$(`select-${s}`).value==='upload';$(`upload-${s}`).hidden=!upload;let strategy;try{strategy=selected(s);}catch{}$(`description-${s}`).textContent=strategy?.description||(upload?'Uses your uploaded Python strategy.':'');$(`source-${s}`).textContent=strategy?.source||'Choose a .py file to preview its source.';if(!record){$(`name-${s}`).textContent=strategy?.name||'Uploaded strategy';$(`faction-${s}`).textContent=$(`label-${s}`).value;}}
for(const s of ['a','b']){
 preview(s);$(`select-${s}`).onchange=()=>preview(s);$(`label-${s}`).onchange=()=>preview(s);
 $(`file-${s}`).onchange=async e=>{const f=e.target.files[0];delete uploads[s];if(!f){preview(s);return;}reading++;$('run').disabled=true;try{if(!f.name.toLowerCase().endsWith('.py'))throw Error('Choose a .py file.');if(f.size>100000)throw Error('File exceeds the 100 KB limit.');const source=await f.text();uploads[s]={id:'upload',name:f.name.replace(/\.py$/i,''),filename:f.name,source,description:'Uploaded strategy · validated at match start.'};$(`file-status-${s}`).textContent=`${f.name} · ${f.size.toLocaleString()} bytes · ready for validation`;}catch(err){$(`file-status-${s}`).textContent=err.message;}finally{reading--;$('run').disabled=busy||reading>0;preview(s);}};
}
$('payoffs').innerHTML=`<table><thead><tr><th>A / B</th><th>B shares</th><th>B keeps</th></tr></thead><tbody><tr><th>A shares</th><td>${RULES.payoffs.SS.join(' / ')}</td><td>${RULES.payoffs.SK.join(' / ')}</td></tr><tr><th>A keeps</th><td>${RULES.payoffs.KS.join(' / ')}</td><td>${RULES.payoffs.KK.join(' / ')}</td></tr></tbody></table>`;
$('generate-seed').onclick=()=>{$('seed').value=seed();};
document.querySelectorAll('[data-rounds]').forEach(b=>b.onclick=()=>{$('rounds').value=b.dataset.rounds;});
const playback=new Playback(renderPlayback);
if(matchMedia('(prefers-reduced-motion: reduce)').matches)$('speed').value='0';
function setBusy(value){busy=value;$('setup-fields').disabled=value;$('run').disabled=value||reading>0;$('cancel').hidden=!value;$('same').disabled=value||!record;$('new').disabled=value||!record;}
async function settings(){const rounds=Number($('rounds').value);if(!Number.isInteger(rounds)||rounds<1||rounds>RULES.maxRounds)throw Error('Choose an integer from 1 to 5,000 rounds.');if(!$('seed').value.trim())throw Error('Enter or generate a seed.');const result={rounds,seed:$('seed').value};for(const s of ['a','b']){const strategy=selected(s);result[s]={...strategy,team:$(`team-${s}`).value,faction:$(`label-${s}`).value,hash:await hashSource(strategy.source)};}return result;}
async function run(existing){if(busy||reading)return;setBusy(true);try{const config=existing||await settings();record=null;playback.load([]);$('analysis').innerHTML='<p class="empty">Computing the match. Analysis appears after playback reaches the end.</p>';$('result-state').textContent='COMPUTING';$('round-csv').disabled=$('summary-csv').disabled=true;$('compute-progress').value=0;for(const s of ['a','b']){$(`name-${s}`).textContent=config[s].team||config[s].name;$(`faction-${s}`).textContent=config[s].faction;}$('snapshot').textContent=`${config.rounds} rounds · seed ${config.seed} · resource multiplier 1.0`;$('round-label').innerHTML=`ROUND<br><b>0 / ${config.rounds}</b>`;$('status').classList.remove('error');engine=new MatchEngine();record=await engine.run(config,(done,total)=>{$('compute-progress').value=done/total*100;$('status').textContent=`Computing: ${done.toLocaleString()} / ${total.toLocaleString()} rounds`},stage=>{$('status').textContent=stage;});
 $('status').textContent=record.error?`${record.status.toUpperCase()} · ${record.error} · ${record.rows.length} completed rounds preserved.`:`Computation complete: ${record.rows.length} rounds. Playback uses this saved record.`;$('status').classList.toggle('error',!!record.error);$('compute-progress').value=record.rows.length/record.rounds*100;$('round-csv').disabled=$('summary-csv').disabled=false;
 $('snapshot').textContent=`${record.rounds} rounds · seed ${record.seed} · A ${record.a.hash.slice(0,8)} / B ${record.b.hash.slice(0,8)} · ${record.timestamp}`;
 playback.delay=Number($('speed').value);playback.load(record.rows);if(record.rows.length)playback.play();else renderResults();
 }catch(error){$('status').textContent=error.message;$('status').classList.add('error');}finally{engine=null;setBusy(false);}}
$('match-form').onsubmit=e=>{e.preventDefault();run();};
function rerun(newSeed){if(!record)return;const {a,b,rounds}=record;const s=newSeed?seed():record.seed;$('seed').value=s;run({a,b,rounds,seed:s});}
$('same').onclick=()=>rerun(false);$('new').onclick=()=>rerun(true);$('cancel').onclick=()=>engine?.cancel();
$('speed').onchange=()=>{playback.delay=Number($('speed').value);if(playback.playing){playback.pause();playback.play();}};
$('play').onclick=()=>playback.playing?playback.pause():playback.play();$('next').onclick=()=>playback.next();$('replay').onclick=()=>playback.replay();$('skip').onclick=()=>playback.skip();$('scrub').oninput=e=>{playback.pause();playback.seek(Number(e.target.value));};
$('round-csv').onclick=()=>record&&download(`space-dilemma-${record.id}-rounds.csv`,roundCSV(record));$('summary-csv').onclick=()=>record&&download(`space-dilemma-${record.id}-summary.csv`,summaryCSV(record));
function renderPlayback(position,playing){
 const rows=record?.rows||[],last=rows[position-1],has=rows.length>0;for(const id of ['play','next','replay','skip','scrub'])$(id).disabled=!has;$('next').disabled=!has||position>=rows.length;$('play').textContent=playing?'Pause':position===rows.length&&has?'Play again':'Play';$('scrub').max=rows.length||1;$('scrub').value=position;
 $('play-state').textContent=!record?'AWAITING MATCH':position===rows.length?(record.status==='complete'?'PLAYBACK COMPLETE':'INCOMPLETE RUN'):playing?'PLAYING':'PAUSED';
 $('round-label').innerHTML=`ROUND<br><b>${position} / ${record?.rounds||$('rounds').value}</b>`;
 for(const s of ['a','b']){$(`total-${s}`).textContent=(last?.[`total_${s}`]||0).toLocaleString();$(`move-${s}`).innerHTML=last?`${last[`move_${s}`]==='S'?'SHARE':'KEEP'} <small>+${last[`points_${s}`]} points</small>`:'— <small>awaiting move</small>';}
 $('outcome').textContent=last?`Round ${position} · ${last.outcome} · ${last.outcome==='SS'?'Both share':last.outcome==='KK'?'Both keep':last.outcome==='SK'?'A shares, B keeps':'A keeps, B shares'}`:'Decisions are revealed together after each round.';
 drawChart($('chart'),rows,position);
 const visible=rows.slice(Math.max(0,position-100),position);$('history').innerHTML=visible.map(r=>`<tr><td>${r.round}</td><td>${r.move_a}</td><td>${r.move_b}</td><td>${r.points_a} / ${r.points_b}</td><td>${r.total_a} / ${r.total_b}</td></tr>`).join('');
 $('timeline').innerHTML=visible.length?visible.map(r=>`<span class="tile ${r.outcome}" title="Round ${r.round}: A ${r.move_a}, B ${r.move_b}">${r.outcome}</span>`).join(''):'<p class="help">Round outcomes will appear here.</p>';$('timeline-note').textContent=position?`Showing rounds ${Math.max(1,position-99)}–${position}. Full history is available in CSV.`:'Only revealed rounds are shown.';
 if(record&&position===rows.length)renderResults();else{$('result-state').textContent=record?'WAITING FOR PLAYBACK':'NO DATA';$('analysis').innerHTML=`<p class="empty">${record?'Watch the match unfold, or skip to results to reveal the complete analysis.':'Run a match to explore sharing, individual advantage, and combined outcomes.'}</p>`;}
}
const pct=v=>v===null?'N/A':v.toFixed(1)+'%';
function renderResults(){if(!record)return;const m=metrics(record.rows),n=m.completed_rounds,report=summary(record);const complete=record.status==='complete';const result=complete?(m.difference_a_minus_b===0?'Draw':`Strategy ${m.difference_a_minus_b>0?'A':'B'} wins`):'Incomplete · no winner';$('result-state').textContent=record.status.toUpperCase();
 const countRate=(k,p)=>`${m[k]} / ${n} (${pct(m[p])})`;
 const compare=[['Total points',m.total_a,m.total_b],['Average points / round',m.average_a?.toFixed(2)??'N/A',m.average_b?.toFixed(2)??'N/A'],['Share count / completed rounds',countRate('share_a_count','share_a_pct'),countRate('share_b_count','share_b_pct')],['Keep count / completed rounds',countRate('keep_a_count','keep_a_pct'),countRate('keep_b_count','keep_b_pct')],['Kept while opponent shared',countRate('benefit_a_count','benefit_a_pct'),countRate('benefit_b_count','benefit_b_pct')],['Shared while opponent kept',countRate('exposure_a_count','exposure_a_pct'),countRate('exposure_b_count','exposure_b_pct')],['Opening move',m.first_move_a??'N/A',m.first_move_b??'N/A'],['First Keep round',m.first_keep_a??(n?'never':'N/A'),m.first_keep_b??(n?'never':'N/A')]];
 const recovery=m.recovery_status==='not_applicable'?'N/A — no one-sided Keep':m.recovery_status==='observed'?`${m.recovery_rounds} round(s)`:'Not observed before match ended';
 $('analysis').innerHTML=`<h3>${result}</h3>${record.error?`<p class="error report">${esc(record.error)}</p>`:''}<div class="metric-grid"><div class="metric"><span>A−B difference</span><strong>${m.difference_a_minus_b>0?'+':''}${m.difference_a_minus_b}</strong></div><div class="metric"><span>Absolute score gap</span><strong>${m.absolute_gap}</strong></div><div class="metric"><span>Combined points</span><strong>${m.combined_score}</strong></div></div><div class="table-scroll"><table><thead><tr><th>${n} completed rounds</th><th class="a">Strategy A</th><th class="b">Strategy B</th></tr></thead><tbody>${compare.map(row=>`<tr>${row.map((v,i)=>i?`<td>${esc(v)}</td>`:`<th>${esc(v)}</th>`).join('')}</tr>`).join('')}</tbody></table></div><h3>Interaction patterns</h3><table><thead><tr><th>Outcome (A, B)</th><th>All ${n} rounds</th><th>Final ${m.ending_rounds} rounds</th></tr></thead><tbody>${['SS','SK','KS','KK'].map(o=>`<tr><th>${o}</th><td>${m[`outcome_${o}_count`]} / ${n} (${pct(m[`outcome_${o}_pct`])})</td><td>${m[`ending_${o}_count`]} / ${m.ending_rounds} (${pct(m[`ending_${o}_pct`])})</td></tr>`).join('')}</tbody></table><p class="report">Mutual sharing: ${pct(m.mutual_sharing_pct)}. Mutual keeping: ${pct(m.mutual_keeping_pct)}. One-sided keeping (“exploitation outcomes”): ${pct(m.one_sided_keeping_pct)}. Denominator: ${n} completed rounds; these labels describe outcomes, not intent.</p><p class="report">First one-sided Keep: ${m.first_one_sided_keep_round?`round ${m.first_one_sided_keep_round}, by ${m.first_one_sided_keep_side}`:'N/A'}.<br>Recovery to mutual sharing: ${recovery}.</p><div class="note">Combined payoff efficiency: <strong>${pct(m.combined_efficiency_pct)}</strong> (${m.combined_score} / ${6*n} possible points). SS, SK, and KS all yield six combined points. <strong>100% efficiency does not establish mutual cooperation or fairness.</strong></div><h3>Match briefing</h3><p class="report">${esc(report.text)}</p><h3>Questions for your analysis</h3><ol>${report.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol><details><summary>Reproducibility & interpretation</summary><p class="help">Master seed: ${esc(record.seed)}<br>A seed: ${record.seed_a} · B seed: ${record.seed_b}<br>Source SHA-256: A ${esc(record.a.hash)}<br>B ${esc(record.b.hash)}<br>These results belong to the recorded sources and settings, even if setup changes. Rerun buttons use that exact snapshot. Time, external data, or unseeded randomness can break repeatability; only random and math imports are supported here. Climate and Trust have no official formulas in this lab. Faction labels do not establish faction-wide tournament performance.</p></details>`;
}
new ResizeObserver(()=>drawChart($('chart'),record?.rows||[],playback.position)).observe($('chart'));
renderPlayback(0,false);
// Optional browser agent API; ordinary browsers simply use the visible controls.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
 for(const tool of [
  {name:'run_configured_match',description:'Run the currently selected strategies, settings and uploaded sources; update the visible match.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(!input||Object.keys(input).length)throw Error('Expected an empty object');if(busy||reading)throw Error('A match or file read is already in progress');await run();if(!record)throw Error($('status').textContent);return {status:record.status,completed_rounds:record.rows.length,match_id:record.id,error:record.error};}},
  {name:'read_revealed_match',description:'Read the match state and totals revealed so far in playback.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:input=>{if(!input||Object.keys(input).length)throw Error('Expected an empty object');const row=record?.rows[playback.position-1];return {status:record?.status||'no_match',revealed_rounds:playback.position,total_a:row?.total_a||0,total_b:row?.total_b||0};}}
 ]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
}
